name: cppcheck

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  cppcheck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install cppcheck
      run: |
        sudo apt-get install -y cppcheck
    - name: cppcheck mandatory
      run: |
        cppcheck --std=c99 --enable=warning,performance --error-exitcode=1 .
    - name: cppcheck advisory
      run: |
        cppcheck --std=c99 --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction --error-exitcode=0 .
